[project]
name = "4una"
version = "0.1.0"
description = "Build a standardized ride-comfort dataset for route recommendation"
readme = "README.md"
authors = [
    { name = "Kijoon Jeong", email = "jkijoon701@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = []

[project.scripts]
4una = "de4:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "de4"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]
