[project]
name = "dashboard"
version = "0.1.0"
description = "Visualizes ride-comfort data"
requires-python = ">=3.12,<3.13"
dependencies = [
    "boto3>=1.40,<2.0",
    "de4-core",
    "fastapi>=0.120.0",
    "folium>=0.20.0",
    "httpx>=0.28.1",
    "pyarrow>=25.0.1",
    "pyproj>=3.7.2",
    "shapely>=2.1.2",
    "streamlit>=1.62.0",
    "streamlit-folium>=0.27.4",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = ["pytest>=9.1.1"]

[project.scripts]
dashboard = "dashboard:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
