apiVersion: 1

datasources:
  - name: CloudWatch
    uid: cloudwatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: ap-northeast-2
    editable: false
